openapi: 3.0.0
info:
  title: voting
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /votes:
    post:
      summary: Submit Vote
      tags: []
      responses:
        '201':
          description: Created
        '406':
          description: Not Acceptable
      operationId: post-vote
    parameters: []
components:
  schemas: {}
