openapi: 3.0.0
info:
  title: voting
  version: 0.1.0
  contact:
    name: Fraser Votes
    url: fraservotes.com
    email: hello@fraservotes.com
  description: An API that connects the Fraser Votes frontend with Firebase
servers:
  - url: 'https://api.fraservotes.com'
paths:
  /vote:
    post:
      summary: Submit Vote
      tags: []
      responses:
        '201':
          description: Created
        '406':
          description: Not Acceptable
      operationId: post-vote
      description: Submit vote to database
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  type: object
                  properties:
                    auth:
                      type: object
                      properties:
                        uid:
                          type: string
                        token:
                          type: object
                          properties:
                            email:
                              type: string
                data:
                  type: object
                  properties:
                    votes:
                      type: object
            examples: {}
    parameters: []
components:
  schemas: {}
  securitySchemes: {}
