openapi: 3.0.0
info:
  title: voting
  version: '1.0'
servers:
  - url: 'https://api.fraservotes.com'
paths:
  /vote:
    post:
      summary: Submit Vote
      tags: []
      responses:
        '201':
          description: Created
        '406':
          description: Not Acceptable
      operationId: post-vote
      description: Create a GPG encrypted ballot in Firestore.
      parameters: []
    parameters: []
components:
  schemas: {}
  securitySchemes: {}
